language: android
# Turning off caching to avoid caching Issues
cache: false
# Using the new Container-Based Infrastructure
sudo: false
env:
  global:
# Initiating clean Gradle output
    - TERM=dumb
# Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
# General Android settings used in builds
    - ANDROID_TARGET=android-21

before_install:
# Making sure gradlew has executable permissions
    - chmod +x gradlew
    - chmod +x scripts/test_results.py
    - chmod +x scripts/test_results.sh

android:
  components:
# We are using the latest revision of Android SDK Tools
     - platform-tools
     - tools
# The BuildTools version we are using for our project
     - build-tools-21.1.2
# System Image we use to run emulator(s) during tests
     - sys-img-armeabi-v7a-android-21
# Extra support components
     - extra

  licenses:
     - 'android-sdk-license-.+'

script:
  - ./gradlew testDebug --quiet
  
after_script:
  - ./scripts/test_results.sh

